# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "sandbox/modular-mvvm",  ]
  pull_request:
    branches: [ "main", "sandbox/modular-mvvm" ]

jobs:
  build:
    name: Build
    env:
      DEVICE: "iPhone 16e"
      DERIVED_DATA_PATH: "DerivedData"
      
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Build
      with:
       path: /MiseTrack
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
